### ISSUE TITLE
Data en CSV

### ISSUE THREAD

**Issue by iBuitron** [PaulESantos/avesperu#1]
Hola!
Tú transcribiste los datos manualmente a partir de checklist?

Quiero saber si puedo usar el archivo "aves_peru_2024.rda" ya que el como .csv puedo usarlo en un proyecto que tengo.

Gracias!

**Comment by PaulESantos** [comment]
La base de datos se genera mediante código desde el archivo pdf. Puedes usar el archivo que mencionas y hacer referencia al paquete.
